### ISSUE TITLE
cant install this

### ISSUE THREAD

**Issue by Goten87** [TanKode/fivem-lua-sdk#2]
how the hell do i need to install this to my phpstorm/intellij idea?
when i try to add the folder as a SDK it gives me a error
steps i take to add
`Alt+Ctrl+Shift+S` to open the project structure
then i go to `Platform Settings->SDK`
then i pres the green plus button to add a new SDK and select `LUA SDK`
then i select the folder where the `_export.js` is locaded and add then then i get the error:
`The Selected Directory is not a valid home for LUA SDK`

**Comment by onno204** [comment]
Same, Have u gotten it fixed yet?

**Comment by JeffreyBytes** [comment]
I was able to add the SDK using the EmmyLua.

**Comment by To-mos** [comment]
It's recommended to use the official generated natives packaged with the client.
They are located at: `%localappdata%\FiveM\FiveM.app\citizen\scripting\lua\natives_universal.lua`

**Comment by Gummibeer** [comment]
https://plugins.jetbrains.com/plugin/9768-emmylua
